/****************************************************************************
 * libgui
 * Daryl Borth 2009-2026
 * GuiInput.h
 *
 * Platform-agnostic input structures
 ***************************************************************************/
#ifndef GUI_INPUT_H
#define GUI_INPUT_H

#include <cstdint>

/**
 * Universal platform-agnostic button bitmasks
 * Covers Wii, GameCube, and Wii U inputs
 */
enum GuiInputButtons : uint32_t {
	GUI_BTN_NONE    = 0,
	GUI_BTN_A       = (1 << 0),
	GUI_BTN_B       = (1 << 1),
	GUI_BTN_X       = (1 << 2),
	GUI_BTN_Y       = (1 << 3),
	GUI_BTN_1       = (1 << 4),
	GUI_BTN_2       = (1 << 5),
	GUI_BTN_UP      = (1 << 6),
	GUI_BTN_DOWN    = (1 << 7),
	GUI_BTN_LEFT    = (1 << 8),
	GUI_BTN_RIGHT   = (1 << 9),
	GUI_BTN_PLUS    = (1 << 10),   // Plus (Wii/Wii U) / Start (GC)
	GUI_BTN_MINUS   = (1 << 11),   // Minus (Wii/Wii U)
	GUI_BTN_HOME    = (1 << 12),  // Home (Wii/Wii U)
	GUI_TRIGGER_L   = (1 << 13),  // L Trigger / Bumper
	GUI_TRIGGER_R   = (1 << 14),  // R Trigger / Bumper
	GUI_TRIGGER_ZL  = (1 << 15),  // ZL Trigger / GC Z Button
	GUI_TRIGGER_ZR  = (1 << 16),  // ZR Trigger
	GUI_THUMB_L     = (1 << 17),  // Left Stick Click (L3)
	GUI_THUMB_R     = (1 << 18)   // Right Stick Click (R3)
};

/**
 * The universal input payload for UI elements.
 * Generated by the driver layer and consumed by GuiElement::update().
 */
struct GuiInputPadData {
	// Button states
	uint32_t buttons_d; // Pressed this frame (down)
	uint32_t buttons_h; // Held this frame
	uint32_t buttons_r; // Released this frame

	// Pointer/Touch state (Mapped to the virtual canvas dimensions)
	float cursor_x;
	float cursor_y;
	float cursor_angle;
	bool validPointer;  // True if the IR pointer or touch is active on screen
	bool isTouch;       // True if input is direct touch (VPad) vs IR pointer

	// Analog stick states (Normalized to -1.0f through 1.0f)
	float stickX;       // Left analog stick X
	float stickY;       // Left analog stick Y
	float substickX;    // Right analog stick (C-Stick) X
	float substickY;    // Right analog stick (C-Stick) Y

	// Default constructor for clean initialization
	GuiInputPadData() :
		buttons_d(0), buttons_h(0), buttons_r(0),
		cursor_x(0.0f), cursor_y(0.0f), cursor_angle(0.0f),
		validPointer(false), isTouch(false),
		stickX(0.0f), stickY(0.0f),
		substickX(0.0f), substickY(0.0f) {}
};

#endif // GUI_INPUT_H
